### ISSUE TITLE
Django 1.10 and DRF 3.5.3

### ISSUE THREAD

**Issue by danielpadula** [alej0varas/django-registration-rest-framework#9]
Hi! I 've added support for latest apps versions, are you still working on the project? I would like to contribute

**Comment by alej0varas** [comment]
Hi Daniel! I'm not contributing to the project currently but if you send a pull request I'll be glad to merge it.

**Comment by CoreyTrombley** [comment]
Any Updates on this support @danielpadula?

**Comment by danielpadula** [comment]
Hi! I have no continued with the project where I need it but when I got a little free time I´ll fix that.

**Comment by RNogales94** [comment]
I'm going to try fix the deprecated "pattern" too in my local project.
If that works I'm going to make a pull request

**Comment by RNogales94** [comment]
No, I have not anything more, i left this project past year sorry.

Best regards
